channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.9
  - pytorch-lightning=1.5.10
  - matplotlib
  - scikit-learn
  - wandb
  - fire
  - opencv
  - torchaudio
  - torchvision
  - pytorch=1.11.0
  - cpuonly
  - jsonargparse=4.3.1
  - pyg
  - h5py
  - fire
  - ordered-set
  - pandas
  - omegaconf
  - Pillow
  - plotly
  - seaborn
  - numpy
  - cython
  - colour
  - torchmetrics
  - pip
  - submitit
#  - pip:
#      - torchmeta --install-option="--no-deps"
