seed_everything: 72
model:
  gnn_type: gat
  optim: adam
  lr_sch: step
  warmup_start_lr: 1e-3
  warmup_epochs: 250
  sup_finetune_lr: 0.0001563663718906821
  sup_finetune: label_cleansing # [prototune, std_proto, label_cleansing, sinkhorn]
  sup_finetune_epochs: 15
  eta_min: 5e-5
  lr: 0.0001563663718906821
  lr_decay_step: 25000
  lr_decay_rate: 0.5
  weight_decay: 6.059722614369727e-06
  img_orig_size: ${data.img_size_orig}
  batch_size: ${data.batch_size}
  n_support: ${data.n_support}
  n_query: ${data.n_query}
  label_cleansing_opts:
    n_test_runs: 1000
    n_ways: 5
    n_shots: 5
    n_queries: 15
    unbalanced: False
    reduce: null # ['isomap', 'itsa', 'mds', 'lle', 'se', 'pca', 'none']
    inference_semi: transductive # ['transductive', 'inductive', 'inductive_sk']
    d: 5
    alpha: 0.8
    K: 20 # neighbours used for manifold creation
    T: 3 # power to raise probs matrix before sinkhorn algorithm
    lr: 0.00001 # learning rate of fine-tuning
    denoising_iterations: 1000
    beta_pt: 0.5 # power transform power
    best_samples: 3 # number of best samples per class chosen for pseudolabels
    semi_inference_method: transductive # ['transductive', 'inductive']
    sinkhorn_iter: 1
    use_pt: False # [True, False]
  mpnn_loss_fn: ce
  mpnn_dev: cuda
  mpnn_opts:
    _use: True
    loss_cnn: True
    scaling_ce: 1
    adapt: instance
    temperature: 0.2
    output_train_gnn: plain
    graph_params:
      sim_type: "correlation"
      thresh: "no" #0
      set_negative: "hard"
    gnn_params:
      pretrained_path: "no"
      red: 0
      cat: 0
      every: 0
      gnn:
        num_layers: 1 # for gatv2
        aggregator: "add"
        num_heads: 2
        attention: "dot"
        mlp: 1
        dropout_mlp: 0.1
        norm1: 1
        norm2: 1
        res1: 1
        res2: 1
        dropout_1: 0.1
        dropout_2: 0.1
        mult_attr: 0
      classifier:
        neck: 0
        num_classes: 0
        dropout_p: 0.4
        use_batchnorm: 0
  feature_extractor:
    class_path: feature_extractors.feature_extractor.ConvNet
    init_args:
      opt:
        in_planes: 3
        out_planes: 64
        num_stages: 4
        average_end: False
trainer:
  gpus: -1
  #  gradient_clip_val: 0.5
  num_sanity_val_steps: 1
  fast_dev_run: 1
  max_epochs: 1500
  limit_train_batches: 100
  limit_val_batches: 15
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_summary.ModelSummary
      init_args:
        max_depth: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./ckpts/"
        monitor: "val_accuracy"
        save_top_k: 10
        every_n_epochs: 1
        mode: "max"

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 200
        monitor: "val_accuracy"
        mode: "max"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

data:
  dataset: "miniimagenet"
  #  datapath: ../data/
  datapath: /home/ojass/projects/unsupervised-meta-learning/data/untarred/
  full_size_path: /home/ojass/projects/data/processed_images/
  #  full_size_path: ../data/processed_images
  n_support: 1
  n_query: 3
  batch_size: 64
  num_workers: 0
  tfm_method: vicreg
  img_size_orig: [ 84, 84 ]
  img_size_crop: [ 84, 84 ]
  no_aug_support: True