seed_everything: 72
model:
  arch: conv4
  conv_4_out_planes: 64
  projection_out_dim: 128
  data_path: ../data/miniimagenet_84
  input_size: 84
  bsize: 128
  num_workers: 1
  lr: 0.025118864315095822
  optimiser: adam
  scheduler: cosine

data:
  data_path: ${model.data_path}
  input_size: 84
  bsize: 128
  num_workers: 1

trainer:
  gpus: 0
  num_sanity_val_steps: 1
  fast_dev_run: 1
  max_epochs: 50
  check_val_every_n_epoch: 24
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: test
      save_dir: wandb_logs
      log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./ckpts/
        filename: "{epoch}-{loss_epoch:.2f}"
        monitor: "loss_epoch"
        save_top_k: 2
        save_last: True
        every_n_epochs: 1
        mode: min
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: pl_bolts.callbacks.PrintTableMetricsCallback

