seed_everything: 72
model:
  optim: adam
  lr_sch: step
  warmup_start_lr: 1e-3
  warmup_epochs: 250
  sup_finetune_lr: ${model.lr}
  sup_finetune: prototune # [prototune, std_proto, proto_maml]
  ft_freeze_backbone: False
  prototune_use_augs: False
  sup_finetune_epochs: 15 # 15 for prototune
  eta_min: 5e-5
  lr: 0.0001563663718906821
  lr_decay_step: 25000
  lr_decay_rate: 0.5
  weight_decay: 6.059722614369727e-06
  img_orig_size: ${data.img_size_orig}
  batch_size: ${data.batch_size}
  n_support: ${data.n_support}
  n_query: ${data.n_query}
  mpnn_loss_fn: ce
  mpnn_dev: cuda
  mpnn_opts:
    _use: True
    loss_cnn: True
    scaling_ce: 1
    adapt: re_rep
    temperature: 0.2
    output_train_gnn: plain
    graph_params:
      sim_type: "correlation"
      thresh: "no" #0
      set_negative: "hard"
    gnn_params:
      pretrained_path: "no"
      red: 1
      cat: 0
      every: 0
      gnn:
        num_layers: 1
        aggregator: "add"
        num_heads: 2
        attention: "dot"
        mlp: 1
        dropout_mlp: 0.1
        norm1: 1
        norm2: 1
        res1: 1
        res2: 1
        dropout_1: 0.1
        dropout_2: 0.1
        mult_attr: 0
      classifier:
        neck: 1
        num_classes: 0
        dropout_p: 0.4
        use_batchnorm: 0
  feature_extractor:
    class_path: feature_extractors.feature_extractor.CNN_4Layer
    init_args:
      global_pooling: False
      in_channels: 3
      final_maxpool: True
      ada_maxpool: False
trainer:
  gpus: -1
  num_sanity_val_steps: 2
  fast_dev_run: False
  max_epochs: 1500
  check_val_every_n_epoch: 10
  limit_train_batches: 100
  limit_val_batches: 15
  limit_test_batches: 600
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: ${oc.env:SLURM_JOB_ID}
      project: CLR+GAT
      save_dir: wandb_logs
      log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_summary.ModelSummary
      init_args:
        max_depth: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./ckpts/mpnn/${oc.env:SLURM_JOB_ID}
        filename: "{epoch}-{step}-{val_loss:.2f}-{val_accuracy:.3f}-{train_accuracy_epoch:.3f}"
        monitor: "train_accuracy_epoch"
        save_last: True
        save_top_k: 2
        every_n_epochs: 1
        mode: "max"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: callbacks.ConfidenceIntervalCallback
      init_args:
        log_to_wb: True

data:
  dataset: "miniimagenet"
  datapath: /home/nfs/oshirekar/unsupervised_ml/data/
  full_size_path: /home/nfs/oshirekar/unsupervised_ml/data/miniImageNetFullSize/
  n_support: 1
  n_query: 3
  batch_size: 64
  num_workers: 8
  tfm_method: vicreg
  img_size_orig: [ 84, 84 ]
  img_size_crop: [ 84, 84 ]
  no_aug_support: True