seed_everything: 72
model:
  arch: conv4
  conv_4_out_planes: 64
  data_path: ${data.data_path}
  input_size: ${data.input_size}
  bsize: ${data.bsize}
  num_workers: ${data.num_workers}
  lr: 0.025118864315095822
  optimiser: adam
  scheduler: cosine

data:
  data_path: /home/nfs/oshirekar/unsupervised_ml/data/miniImageNetFullSize/
  input_size: 84
  bsize: 128
  num_workers: 8

trainer:
  gpus: -1
  fast_dev_run: 0
  max_epochs: 400
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: NNCLR
      save_dir: wandb_logs
      log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./ckpts/
        filename: "{epoch}-{loss_epoch:.2f}"
        monitor: "loss_epoch"
        save_top_k: 2
        save_last: True
        every_n_epochs: 1
        mode: min
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: pl_bolts.callbacks.PrintTableMetricsCallback