seed_everything: 72
model:
  arch: resnet12_wide
  conv_4_out_planes: 64
  dataset: ${data.dataset}
  optim: adam
  lr_sch: step
  warmup_start_lr: 1e-3
  warmup_epochs: 250
  sup_finetune_lr: 0.0001563663718906821
  sup_finetune: prototune # [prototune, std_proto, proto_maml, sinkhorn]
  sup_finetune_epochs: 15
  use_projector: True
  use_prediction_head: True
  projection_out_dim: 256
  projection_h_dim: 2048
  pred_h_dim: 4096
  eta_min: 5e-5
  lr: 1e-3
  lr_decay_step: 25000
  lr_decay_rate: 0.5
  weight_decay: 6.059722614369727e-06
  img_orig_size: [ 84, 84 ]
  batch_size: ${data.bsize}
  n_support: 1
  n_query: 3
  queue_size: 8192
  adapt: re_rep
  mpnn_loss_fn: ce
  mpnn_dev: cuda
  mpnn_opts:
    _use: False
    loss_cnn: False
    scaling_ce: 1
    adapt: instance
    temperature: 0.2
    output_train_gnn: plain
    graph_params:
      sim_type: "correlation"
      thresh: "no" #0
      set_negative: "hard"
    gnn_params:
      pretrained_path: "no"
      red: 1
      cat: 0
      every: 0
      gnn:
        num_layers: 1 # for gatv2
        aggregator: "add"
        num_heads: 2
        attention: "dot"
        mlp: 1
        dropout_mlp: 0.1
        norm1: 1
        norm2: 1
        res1: 1
        res2: 1
        dropout_1: 0.1
        dropout_2: 0.1
        mult_attr: 0
      classifier:
        neck: 0
        num_classes: 0
        dropout_p: 0.4
        use_batchnorm: 0
trainer:
  gpus: -1
  num_sanity_val_steps: 1
  fast_dev_run: 0
  max_epochs: 1000
  limit_val_batches: 15
  check_val_every_n_epoch: 10
  limit_test_batches: 600
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: ${oc.env:SLURM_JOB_ID}
      project: NNProtoCLR
      save_dir: wandb_logs
      log_model: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_summary.ModelSummary
      init_args:
        max_depth: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./ckpts/"
        monitor: "val_accuracy_epoch"
        save_top_k: 2
        save_last: True
        every_n_epochs: 1
        mode: "max"
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

data:
  dataset: "miniimagenet"
  fsl_data_path: /home/nfs/oshirekar/unsupervised_ml/data/
  data_path: /home/nfs/oshirekar/unsupervised_ml/data/miniimagenet_84/
  input_size: 84
  bsize: 128
  eval_shots: 5
  eval_ways: 5
  eval_query_shots: 15
  num_workers: 8