job_name: local_swav
seed_everything: 72
nmb_crops: [ 2,  6 ]
size_crops: [ 224,  96 ]
min_scale_crops: [ 0.14,  0.05 ]
max_scale_crops: [ 1.0,  0.14 ]
crops_for_assign: [ 0, 1 ]
gaussian_blur: True
jitter_strength: 1.0
input_height: 224

model:
  maxpool1: True
  first_conv: True

  nmb_crops: ${nmb_crops}
  
  batch_size: ${data.batch_size}
  num_nodes: 1
  gpus: 1  # per-node
  max_epochs: ${trainer.max_epochs}
  
  optim: adam
  learning_rate: 4.8
  final_lr: 0.0048
  start_lr: 0.3
  
  nmb_prototypes: 1800

  num_samples: 0
  dataset: miniimagenet
  arch: conv4
  hidden_mlp: 256
  feat_dim: 64
  warmup_epochs: 10
  freeze_prototypes_epochs: 1
  temperature: 0.1
  sinkhorn_iterations: 3
  queue_length: 0   # must be divisible by total batch-size
  queue_path: queue
  epoch_queue_starts: 15
  exclude_bn_bias: False
  weight_decay: 1e-6
  epsilon: 0.05

  sup_finetune: True
  sup_finetune_lr: 1e-3
  sup_finetune_epochs: 15
  ft_freeze_backbone: True
  finetune_batch_norm: False

  kwargs:
    input_height: ${input_height}
    size_crops: ${size_crops}
    min_scale_crops: ${min_scale_crops}
    max_scale_crops: ${max_scale_crops}
    crops_for_assign: ${crops_for_assign}
    gaussian_blur: ${gaussian_blur}
    jitter_strength: ${jitter_strength}
  mpnn_opts:
    _use: False
    loss_cnn: True
    scaling_ce: 1
    task_adapt: False
    temperature: 0.2
    output_train_gnn: plain
    graph_params:
      sim_type: "correlation"
      thresh: "no" #0
      set_negative: "hard"
    gnn_params:
      pretrained_path: "no"
      red: 1
      cat: 0
      every: 0
      gnn:
        num_layers: 1
        aggregator: "add"
        num_heads: 1
        attention: "dot"
        mlp: 1
        dropout_mlp: 0.1
        norm1: 1
        norm2: 1
        res1: 1
        res2: 1
        dropout_1: 0.1
        dropout_2: 0.1
        mult_attr: 0
      classifier:
        neck: 1
        num_classes: 0
        dropout_p: 0.4
        use_batchnorm: 0


data:
  fsl_datapath: /home/ojass/projects/unsupervised-meta-learning/data/untarred/
  data_dir: /home/ojass/projects/data/processed_images/
  eval_ways: 5
  eval_support_shots: 5
  eval_query_shots: 15
  batch_size: 10
  num_workers: 8

trainer:
  fast_dev_run: 1
  max_epochs: 800
  check_val_every_n_epoch: 10
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_summary.ModelSummary
      init_args:
        max_depth: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./ckpts/${job_name}
        filename: "{epoch}-{step}-{val_loss:.2f}-{val_accuracy:.3f}-{train_accuracy_epoch:.3f}"
        monitor: "val_loss"
        save_last: True
        save_top_k: 1
        mode: min
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step