seed_everything: 72
model:
  data_path: ../data/miniimagenet_84/train
  batch_size: 4
  num_workers: 1
trainer:
  gpus: 0
  num_sanity_val_steps: 1
  fast_dev_run: 1
  max_epochs: 10
  limit_train_batches: 100
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_summary.ModelSummary
      init_args:
        max_depth: 3
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./ckpts/"
        monitor: "val_accuracy"
        save_top_k: 10
        every_n_epochs: 1
        mode: "max"
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: loss
        mode: min
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"